name:        Eduardo Ferreira
description: This site provides an overview of my professional career, personal interests and current projects.

user:    Eduardo Ferreira
url:     http://eduardoferreira.me
baseurl: /

markdown:    rdiscount
permalink:   pretty
safe:        true
lsi:         false
highlighter: pygments
